name: neural_bandits
channels:
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
dependencies:
  - python=3.10 # or don't specify the version and use latest stable
  - wandb
  - lightning

  # Good to have
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - ucimlrepo

  # Misc
  - tqdm
  - kagglehub

  # Dev dependencies
  - black
  - ruff
  - isort
  - mypy
  - pytest
  - pytest-cov

  # pip dependencies
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - simple_parsing
      - print-on-steroids[exceptions]
      - wandb[sweeps]
