site_name: Documentation for Calvera
repo_url: https://github.com/neural-bandits/calvera
repo_name: neural_bandits/calvera

markdown_extensions: 
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

theme:
  name: material
  logo: calvera-light.png
  favicon: calvera-light.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: white
      logo: calvera-light.png
      favicon: calvera-light.png

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      logo: calvera-light.png
      favicon: calvera-light.png

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      logo: calvera-dark.png
      favicon: calvera-dark.png

  icon:
    repo: fontawesome/brands/git-alt
  features:
      - header.autohide
      - navigation.footer
      - navigation.tabs
      - navigation.indexes

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
nav:
  - Docs: index.md
  - Examples: examples.md
  - API Reference:
      - Bandit Interface: bandits.md
      - LinearTS and LinearUCB: linear_ts_and_linear_ucb.md
      - NeuralTS and NeuralUCB: neural_ts_and_neural_ucb.md
      - Neural Linear Bandit: neural_linear_bandit.md
      - Buffers: buffers.md
      - Utils: utils.md
      - Benchmark: benchmark.md
