name: Build GitHub Pages
on:
  push:
    branches:
      - main
      # - docs # Could be nice for testing before pushing to main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Make sure that the build and deploy jobs run in sequence to avoid merge conflicts.
concurrency:
  group: build_deploy_gh_pages
  cancel-in-progress: false

jobs:
  build_and_deploy_mkdocs:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install mkdocstrings
      - run: pip install \
            mkdocs-material
      - run: mkdocs gh-deploy --config-file mkdocs.yml --force
