name: Build GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Make sure that the build and deploy jobs run in sequence to avoid merge conflicts.
concurrency:
  group: build_deploy_gh_pages
  cancel-in-progress: false

jobs:
  build_and_deploy_mkdocs:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install Neural-Bandits
        run: pip3 install -e . --extra-index-url https://download.pytorch.org/whl/cpu
        shell: bash

      - name: Install dev dependencies
        run: pip3 install -e .[dev]
        shell: bash

      - name: Build documentation
        run: mkdocs build --config-file mkdocs.yml
        shell: bash

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4